In [1]:
# lapply
# list apply, always returns a list.

x = list(a=1:5, b=rnorm(10))
lapply(x, mean)

$a
[1] 3

$b
[1] -0.02773754

In [2]:
help(rnorm)

Normal                  package:stats                  R Documentation

_T_h_e _N_o_r_m_a_l _D_i_s_t_r_i_b_u_t_i_o_n

_D_e_s_c_r_i_p_t_i_o_n:

     Density, distribution function, quantile function and random
     generation for the normal distribution with mean equal to ‘mean’
     and standard deviation equal to ‘sd’.

_U_s_a_g_e:

     dnorm(x, mean = 0, sd = 1, log = FALSE)
     pnorm(q, mean = 0, sd = 1, lower.tail = TRUE, log.p = FALSE)
     qnorm(p, mean = 0, sd = 1, lower.tail = TRUE, log.p = FALSE)
     rnorm(n, mean = 0, sd = 1)
     
_A_r_g_u_m_e_n_t_s:

    x, q: vector of quantiles.

       p: vector of probabilities.

       n: number of observations. If ‘length(n) > 1’, the length is
          taken to be the number required.

    mean: vector of means.

      sd: vector of standard deviations.

log, log.p: logical; if TRUE, probabilities p are given as log(p).

lower.tail: logical; if TRUE (default), probabilities are P[X <= x]
          otherwise, P[X > x].

_D_e_t_a_i_l_s:

     If ‘mean’ or ‘sd’ are not specified they assume the default values
     of ‘0’ and ‘1’, respectively.

     The normal distribution has density

            f(x) = 1/(sqrt(2 pi) sigma) e^-((x - mu)^2/(2 sigma^2))     
     
     where mu is the mean of the distribution and sigma the standard
     deviation.

_V_a_l_u_e:

     ‘dnorm’ gives the density, ‘pnorm’ gives the distribution
     function, ‘qnorm’ gives the quantile function, and ‘rnorm’
     generates random deviates.

     The length of the result is determined by ‘n’ for ‘rnorm’, and is
     the maximum of the lengths of the numerical arguments for the
     other functions.

     The numerical arguments other than ‘n’ are recycled to the length
     of the result.  Only the first elements of the logical arguments
     are used.

     For ‘sd = 0’ this gives the limit as ‘sd’ decreases to 0, a point
     mass at ‘mu’.  ‘sd < 0’ is an error and returns ‘NaN’.

_S_o_u_r_c_e:

     For ‘pnorm’, based on

     Cody, W. D. (1993) Algorithm 715: SPECFUN - A portable FORTRAN
     package of special function routines and test drivers.  _ACM
     Transactions on Mathematical Software_ *19*, 22-32.

     For ‘qnorm’, the code is a C translation of

     Wichura, M. J. (1988) Algorithm AS 241: The percentage points of
     the normal distribution.  _Applied Statistics_, *37*, 477-484.

     which provides precise results up to about 16 digits.

     For ‘rnorm’, see RNG for how to select the algorithm and for
     references to the supplied methods.

_R_e_f_e_r_e_n_c_e_s:

     Becker, R. A., Chambers, J. M. and Wilks, A. R. (1988) _The New S
     Language_.  Wadsworth & Brooks/Cole.

     Johnson, N. L., Kotz, S. and Balakrishnan, N. (1995) _Continuous
     Univariate Distributions_, volume 1, chapter 13.  Wiley, New York.

_S_e_e _A_l_s_o:

     Distributions for other standard distributions, including ‘dlnorm’
     for the _Log_normal distribution.

_E_x_a_m_p_l_e_s:

     require(graphics)
     
     dnorm(0) == 1/sqrt(2*pi)
     dnorm(1) == exp(-1/2)/sqrt(2*pi)
     dnorm(1) == 1/sqrt(2*pi*exp(1))
     
     ## Using "log = TRUE" for an extended range :
     par(mfrow = c(2,1))
     plot(function(x) dnorm(x, log = TRUE), -60, 50,
          main = "log { Normal density }")
     curve(log(dnorm(x)), add = TRUE, col = "red", lwd = 2)
     mtext("dnorm(x, log=TRUE)", adj = 0)
     mtext("log(dnorm(x))", col = "red", adj = 1)
     
     plot(function(x) pnorm(x, log.p = TRUE), -50, 10,
          main = "log { Normal Cumulative }")
     curve(log(pnorm(x)), add = TRUE, col = "red", lwd = 2)
     mtext("pnorm(x, log=TRUE)", adj = 0)
     mtext("log(pnorm(x))", col = "red", adj = 1)
     
     ## if you want the so-called 'error function'
     erf <- function(x) 2 * pnorm(x * sqrt(2)) - 1
     ## (see Abramowitz and Stegun 29.2.29)
     ## and the so-called 'complementary error function'
     erfc <- 

In [3]:
x

$a
[1] 1 2 3 4 5

$b
 [1]  0.83618610  0.02419287 -0.06169286 -0.22582268 -0.84710044  0.93183222
 [7]  0.51951416 -1.06250572  1.24392997 -1.63590903

In [4]:
# random uniform has the same probability for all values.
help(runif)

Uniform                 package:stats                  R Documentation

_T_h_e _U_n_i_f_o_r_m _D_i_s_t_r_i_b_u_t_i_o_n

_D_e_s_c_r_i_p_t_i_o_n:

     These functions provide information about the uniform distribution
     on the interval from ‘min’ to ‘max’.  ‘dunif’ gives the density,
     ‘punif’ gives the distribution function ‘qunif’ gives the quantile
     function and ‘runif’ generates random deviates.

_U_s_a_g_e:

     dunif(x, min = 0, max = 1, log = FALSE)
     punif(q, min = 0, max = 1, lower.tail = TRUE, log.p = FALSE)
     qunif(p, min = 0, max = 1, lower.tail = TRUE, log.p = FALSE)
     runif(n, min = 0, max = 1)
     
_A_r_g_u_m_e_n_t_s:

    x, q: vector of quantiles.

       p: vector of probabilities.

       n: number of observations. If ‘length(n) > 1’, the length is
          taken to be the number required.

min, max: lower and upper limits of the distribution.  Must be finite.

log, log.p: logical; if TRUE, probabilities p are given as log(p).

lower.tail: logical; if TRUE (default), probabilities are P[X <= x],
          otherwise, P[X > x].

_D_e_t_a_i_l_s:

     If ‘min’ or ‘max’ are not specified they assume the default values
     of ‘0’ and ‘1’ respectively.

     The uniform distribution has density

                             f(x) = 1/(max-min)                         
     
     for min <= x <= max.

     For the case of u := min == max, the limit case of X == u is
     assumed, although there is no density in that case and ‘dunif’
     will return ‘NaN’ (the error condition).

     ‘runif’ will not generate either of the extreme values unless ‘max
     = min’ or ‘max-min’ is small compared to ‘min’, and in particular
     not for the default arguments.

_V_a_l_u_e:

     ‘dunif’ gives the density, ‘punif’ gives the distribution
     function, ‘qunif’ gives the quantile function, and ‘runif’
     generates random deviates.

     The length of the result is determined by ‘n’ for ‘runif’, and is
     the maximum of the lengths of the numerical arguments for the
     other functions.

     The numerical arguments other than ‘n’ are recycled to the length
     of the result.  Only the first elements of the logical arguments
     are used.

_N_o_t_e:

     The characteristics of output from pseudo-random number generators
     (such as precision and periodicity) vary widely.  See
     ‘.Random.seed’ for more information on R's random number
     generation algorithms.

_R_e_f_e_r_e_n_c_e_s:

     Becker, R. A., Chambers, J. M. and Wilks, A. R. (1988) _The New S
     Language_.  Wadsworth & Brooks/Cole.

_S_e_e _A_l_s_o:

     ‘RNG’ about random number generation in R.

     Distributions for other standard distributions.

_E_x_a_m_p_l_e_s:

     u <- runif(20)
     
     ## The following relations always hold :
     punif(u) == u
     dunif(u) == 1
     
     var(runif(10000))  #- ~ = 1/12 = .08333

In [5]:
# we can use the ... var to pass variable we want to give the function that we apply to the list.
x = 1:4
lapply(x, runif, min=0, max=10)

[[1]]
[1] 0.7828821

[[2]]
[1] 5.537273 6.528638

[[3]]
[1] 3.258560 4.999528 5.438921

[[4]]
[1] 1.745172 2.060851 8.032201 1.792619

In [6]:
# lapply often use "anonymous functions"
x = list(a=matrix(1:4, 2,2), b=matrix(1:6, 3, 2))
x

$a
     [,1] [,2]
[1,]    1    3
[2,]    2    4

$b
     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6

In [7]:
# use this simple anonymous function, we can get the first column of each matrix in the list.
lapply(x, function(elt) elt[,1])

$a
[1] 1 2

$b
[1] 1 2 3

<h2>sapply</h2>

In [19]:
str(sapply)
str(lapply)

function (X, FUN, ..., simplify = TRUE, USE.NAMES = TRUE)  
function (X, FUN, ...)  


In [10]:
# sapply is simplifying the result of lapply if possible
# if it returns a list with only numbers in each element, than it returns a vector.
x = list(a=1:4, b=rnorm(4), c=runif(4), d=rnorm(10), e=rnorm(100,5))
lapply(x, mean)
sapply(x, mean)

$a
[1] 2.5

$b
[1] -0.01722031

$c
[1] 0.5018457

$d
[1] -0.02499991

$e
[1] 5.035901

a           b           c           d           e 
 2.50000000 -0.01722031  0.50184568 -0.02499991  5.03590070

<h2>apply</h2>
It's not really faster than loop, the only reason we use, is because it fits in one line.
Useful in command line

In [14]:
x = matrix(rnorm(200), 20, 10)

# 2 is the dimension(margin) we want to keep,
# 2 means, we're calculating the mean of each column of this matrix.
apply(x, 2, mean)
colMeans(x)

[1]  0.10831600  0.09842825  0.13040679  0.09270295 -0.39638955  0.06464242
 [7] -0.01841609 -0.18051775 -0.14064699  0.02512436

[1]  0.10831600  0.09842825  0.13040679  0.09270295 -0.39638955  0.06464242
 [7] -0.01841609 -0.18051775 -0.14064699  0.02512436

In [15]:
# preserve the row.
apply(x, 1, sum)
rowSums(x)

[1]  2.9855247  0.2149290  2.4593127  0.3376165  1.2644430 -0.4036006
 [7] -0.7528885  2.2750487  1.4041443 -0.5026537 -1.6168208  1.3374845
[13] -0.1134105 -2.0432512 -0.9248568 -3.7491503 -2.4386323 -8.6850636
[19]  5.5980766 -0.9732436

[1]  2.9855247  0.2149290  2.4593127  0.3376165  1.2644430 -0.4036006
 [7] -0.7528885  2.2750487  1.4041443 -0.5026537 -1.6168208  1.3374845
[13] -0.1134105 -2.0432512 -0.9248568 -3.7491503 -2.4386323 -8.6850636
[19]  5.5980766 -0.9732436

In [17]:
# there are some optimized functions
# way much faster !!!!
rowSums = apply(x, 2, sum)
rowMeans = apply(x, 2, mean)
colSums = apply(x, 1, sum)
colMeans = apply(x, 1, mean)

In [18]:
help(quantile)

quantile                 package:stats                 R Documentation

_S_a_m_p_l_e _Q_u_a_n_t_i_l_e_s

_D_e_s_c_r_i_p_t_i_o_n:

     The generic function ‘quantile’ produces sample quantiles
     corresponding to the given probabilities.  The smallest
     observation corresponds to a probability of 0 and the largest to a
     probability of 1.

_U_s_a_g_e:

     quantile(x, ...)
     
     ## Default S3 method:
     quantile(x, probs = seq(0, 1, 0.25), na.rm = FALSE,
              names = TRUE, type = 7, ...)
     
_A_r_g_u_m_e_n_t_s:

       x: numeric vector whose sample quantiles are wanted, or an
          object of a class for which a method has been defined (see
          also ‘details’). ‘NA’ and ‘NaN’ values are not allowed in
          numeric vectors unless ‘na.rm’ is ‘TRUE’.

   probs: numeric vector of probabilities with values in [0,1].
          (Values up to ‘2e-14’ outside that range are accepted and
          moved to the nearby endpoint.)

   na.rm: logical; if true, any ‘NA’ and ‘NaN’'s are removed from ‘x’
          before the quantiles are computed.

   names: logical; if true, the result has a ‘names’ attribute.  Set to
          ‘FALSE’ for speedup with many ‘probs’.

    type: an integer between 1 and 9 selecting one of the nine quantile
          algorithms detailed below to be used.

     ...: further arguments passed to or from other methods.

_D_e_t_a_i_l_s:

     A vector of length ‘length(probs)’ is returned; if ‘names = TRUE’,
     it has a ‘names’ attribute.

     ‘NA’ and ‘NaN’ values in ‘probs’ are propagated to the result.

     The default method works with classed objects sufficiently like
     numeric vectors that ‘sort’ and (not needed by types 1 and 3)
     addition of elements and multiplication by a number work
     correctly.  Note that as this is in a namespace, the copy of
     ‘sort’ in ‘base’ will be used, not some S4 generic of that name.
     Also note that that is no check on the ‘correctly’, and so e.g.
     ‘quantile’ can be applied to complex vectors which (apart from
     ties) will be ordered on their real parts.

     There is a method for the date-time classes (see ‘"POSIXt"’).
     Types 1 and 3 can be used for class ‘"Date"’ and for ordered
     factors.

_T_y_p_e_s:

     ‘quantile’ returns estimates of underlying distribution quantiles
     based on one or two order statistics from the supplied elements in
     ‘x’ at probabilities in ‘probs’.  One of the nine quantile
     algorithms discussed in Hyndman and Fan (1996), selected by
     ‘type’, is employed.

     All sample quantiles are defined as weighted averages of
     consecutive order statistics. Sample quantiles of type i are
     defined by:

                 Q[i](p) = (1 - gamma) x[j] + gamma x[j+1],             
     
     where 1 <= i <= 9, (j-m)/n <= p < (j-m+1)/n, x[j] is the jth order
     statistic, n is the sample size, the value of gamma is a function
     of j = floor(np + m) and g = np + m - j, and m is a constant
     determined by the sample quantile type.

     *Discontinuous sample quantile types 1, 2, and 3*

     For types 1, 2 and 3, Q[i](p) is a discontinuous function of p,
     with m = 0 when i = 1 and i = 2, and m = -1/2 when i = 3.

     Type 1 Inverse of empirical distribution function.  gamma = 0 if g
          = 0, and 1 otherwise.

     Type 2 Similar to type 1 but with averaging at discontinuities.
          gamma = 0.5 if g = 0, and 1 otherwise.

     Type 3 SAS definition: nearest even order statistic.  gamma = 0 if
          g = 0 and j is even, and 1 otherwise.

     *Continuous sample quantile types 4 through 9*

     For types 4 through 9, Q[i](p) is a continuous function of p, with
     gamma = g and m given below. The sample quantiles can be obtained
     equivalently by linear interpolation between the points
     (p[k],x[k]) where x[k] is the kth order statistic.  Specific
     expressions for p[k] are given below.


In [24]:
quantile(c(1,2,3,4,5,6,7), prob=c(0.25, 0.75))

25% 75% 
2.5 5.5

In [25]:
x = matrix(rnorm(200), 20, 10)
apply(x, 1, quantile, prob = c(0.25, 0.75))

[,1]       [,2]       [,3]       [,4]       [,5]       [,6]
25% -0.9123826 -0.2816344 -0.6583084 -0.9391186 -0.1970139 -0.4218560
75%  0.4854153  0.7817871  1.0712998  0.5538968  0.9508606  0.6674913
          [,7]       [,8]       [,9]      [,10]      [,11]      [,12]
25% -0.1987485 -0.4120650 -0.7836675 -0.1603253 -0.9018405 -0.7511502
75%  0.3371495  0.3140514  0.1996391  1.3081357 -0.0620048  0.6661210
         [,13]      [,14]       [,15]      [,16]      [,17]      [,18]
25% 0.08186614 -0.6970578 -0.79185089 -1.2364485 -0.5197554 -0.4833428
75% 1.00288862  0.7591118  0.09213262  0.2977238  0.9715987  0.7329413
         [,19]       [,20]
25% -0.5155774 -0.06126219
75% -0.2031866  0.87167855

In [26]:
help(array)

array                   package:base                   R Documentation

_M_u_l_t_i-_w_a_y _A_r_r_a_y_s

_D_e_s_c_r_i_p_t_i_o_n:

     Creates or tests for arrays.

_U_s_a_g_e:

     array(data = NA, dim = length(data), dimnames = NULL)
     as.array(x, ...)
     is.array(x)
     
_A_r_g_u_m_e_n_t_s:

    data: a vector (including a list or ‘expression’ vector) giving
          data to fill the array.  Non-atomic classed objects are
          coerced by ‘as.vector’.

     dim: the dim attribute for the array to be created, that is an
          integer vector of length one or more giving the maximal
          indices in each dimension.

dimnames: either ‘NULL’ or the names for the dimensions.  This must a
          list (or it will be ignored) with one component for each
          dimension, either ‘NULL’ or a character vector of the length
          given by ‘dim’ for that dimension.  The list can be named,
          and the list names will be used as names for the dimensions.
          If the list is shorter than the number of dimensions, it is
          extended by ‘NULL’s to the length required.

       x: an R object.

     ...: additional arguments to be passed to or from methods.

_D_e_t_a_i_l_s:

     An array in R can have one, two or more dimensions.  It is simply
     a vector which is stored with additional attributes giving the
     dimensions (attribute ‘"dim"’) and optionally names for those
     dimensions (attribute ‘"dimnames"’).

     A two-dimensional array is the same thing as a ‘matrix’.

     One-dimensional arrays often look like vectors, but may be handled
     differently by some functions: ‘str’ does distinguish them in
     recent versions of R.

     The ‘"dim"’ attribute is an integer vector of length one or more
     containing non-negative values: the product of the values must
     match the length of the array.

     The ‘"dimnames"’ attribute is optional: if present it is a list
     with one component for each dimension, either ‘NULL’ or a
     character vector of the length given by the element of the ‘"dim"’
     attribute for that dimension.

     ‘is.array’ is a primitive function.

     For a list array, the ‘print’ methods prints entries of length not
     one in the form ‘integer,7’ indicating the type and length.

_V_a_l_u_e:

     ‘array’ returns an array with the extents specified in ‘dim’ and
     naming information in ‘dimnames’.  The values in ‘data’ are taken
     to be those in the array with the leftmost subscript moving
     fastest.  If there are too few elements in ‘data’ to fill the
     array, then the elements in ‘data’ are recycled.  If ‘data’ has
     length zero, ‘NA’ of an appropriate type is used for atomic
     vectors (‘0’ for raw vectors) and ‘NULL’ for lists.

     Unlike ‘matrix’, ‘array’ does not currently remove any attributes
     left by ‘as.vector’ from a classed list ‘data’, so can return a
     list array with a class attribute.

     ‘as.array’ is a generic function for coercing to arrays.  The
     default method does so by attaching a ‘dim’ attribute to it.  It
     also attaches ‘dimnames’ if ‘x’ has ‘names’.  The sole purpose of
     this is to make it possible to access the ‘dim[names]’ attribute
     at a later time.

     ‘is.array’ returns ‘TRUE’ or ‘FALSE’ depending on whether its
     argument is an array (i.e., has a ‘dim’ attribute of positive
     length) or not.  It is generic: you can write methods to handle
     specific classes of objects, see InternalMethods.

_N_o_t_e:

     ‘is.array’ is a primitive function.

     R 2.x.y allowed (although documented not to) a zero-length ‘dim’
     argument, and returned a vector of length one.

_R_e_f_e_r_e_n_c_e_s:

     Becker, R. A., Chambers, J. M. and Wilks, A. R. (1988) _The New S
     Language_.  Wadsworth & Brooks/Cole.

_S_e_e _A_l_s_o:

     ‘aperm’, ‘matrix’, ‘dim’, ‘dimnames’.

_E_x_a_m_p_l_e_s:

     dim(as

In [38]:
# Play with Array
# A two-dimensional array is the same thing as a matrix.

# One-dimensional arrays often look like vectors, but may be handled differently by some 
# functions: str does distinguish them in recent versions of R.

a = array(1:200, c(4,5,10))
a[,,2]
a[1,,]

[,1] [,2] [,3] [,4] [,5]
[1,]   21   25   29   33   37
[2,]   22   26   30   34   38
[3,]   23   27   31   35   39
[4,]   24   28   32   36   40

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]    1   21   41   61   81  101  121  141  161   181
[2,]    5   25   45   65   85  105  125  145  165   185
[3,]    9   29   49   69   89  109  129  149  169   189
[4,]   13   33   53   73   93  113  133  153  173   193
[5,]   17   37   57   77   97  117  137  157  177   197

In [48]:
apply(a, c(2,3), mean)

[,1] [,2] [,3] [,4] [,5]  [,6]  [,7]  [,8]  [,9] [,10]
[1,]  2.5 22.5 42.5 62.5 82.5 102.5 122.5 142.5 162.5 182.5
[2,]  6.5 26.5 46.5 66.5 86.5 106.5 126.5 146.5 166.5 186.5
[3,] 10.5 30.5 50.5 70.5 90.5 110.5 130.5 150.5 170.5 190.5
[4,] 14.5 34.5 54.5 74.5 94.5 114.5 134.5 154.5 174.5 194.5
[5,] 18.5 38.5 58.5 78.5 98.5 118.5 138.5 158.5 178.5 198.5

In [49]:
apply(a, c(1), mean)
rowMeans(a, dims=1)

[1]  99 100 101 102

[1]  99 100 101 102

In [47]:
colMeans(a, dims=1)

[,1] [,2] [,3] [,4] [,5]  [,6]  [,7]  [,8]  [,9] [,10]
[1,]  2.5 22.5 42.5 62.5 82.5 102.5 122.5 142.5 162.5 182.5
[2,]  6.5 26.5 46.5 66.5 86.5 106.5 126.5 146.5 166.5 186.5
[3,] 10.5 30.5 50.5 70.5 90.5 110.5 130.5 150.5 170.5 190.5
[4,] 14.5 34.5 54.5 74.5 94.5 114.5 134.5 154.5 174.5 194.5
[5,] 18.5 38.5 58.5 78.5 98.5 118.5 138.5 158.5 178.5 198.5

<h2>mapply</h2>
a multivariate apply. 
For example, we might use for loop and loop through two list at the same time, so we can access both list.
and mapply is here for the same usage.

In [50]:
help(rep)

rep                    package:base                    R Documentation

_R_e_p_l_i_c_a_t_e _E_l_e_m_e_n_t_s _o_f _V_e_c_t_o_r_s _a_n_d _L_i_s_t_s

_D_e_s_c_r_i_p_t_i_o_n:

     ‘rep’ replicates the values in ‘x’.  It is a generic function, and
     the (internal) default method is described here.

     ‘rep.int’ and ‘rep_len’ are faster simplified versions for two
     common cases.  They are not generic.

_U_s_a_g_e:

     rep(x, ...)
     
     rep.int(x, times)
     
     rep_len(x, length.out)
     
_A_r_g_u_m_e_n_t_s:

       x: a vector (of any mode including a list) or a factor or (for
          ‘rep’ only) a ‘POSIXct’ or ‘POSIXlt’ or ‘Date’ object; or an
          S4 object containing such an object.

     ...: further arguments to be passed to or from other methods.  For
          the internal default method these can include:

          ‘times’ A integer vector giving the (non-negative) number of
              times to repeat each element if of length ‘length(x)’, or
              to repeat the whole vector if of length 1.  Negative or
              ‘NA’ values are an error.

          ‘length.out’ non-negative integer.  The desired length of the
              output vector.  Other inputs will be coerced to an
              integer vector and the first element taken.  Ignored if
              ‘NA’ or invalid.

          ‘each’ non-negative integer.  Each element of ‘x’ is repeated
              ‘each’ times.  Other inputs will be coerced to an integer
              vector and the first element taken.  Treated as ‘1’ if
              ‘NA’ or invalid.

   times: see ‘...’.

length.out: non-negative integer: the desired length of the output
          vector.

_D_e_t_a_i_l_s:

     The default behaviour is as if the call was
     
       rep(x, times = 1, length.out = NA, each = 1)
     .  Normally just one of the additional arguments is specified, but
     if ‘each’ is specified with either of the other two, its
     replication is performed first, and then that implied by ‘times’
     or ‘length.out’.

     If ‘times’ consists of a single integer, the result consists of
     the whole input repeated this many times.  If ‘times’ is a vector
     of the same length as ‘x’ (after replication by ‘each’), the
     result consists of ‘x[1]’ repeated ‘times[1]’ times, ‘x[2]’
     repeated ‘times[2]’ times and so on.

     ‘length.out’ may be given in place of ‘times’, in which case ‘x’
     is repeated as many times as is necessary to create a vector of
     this length.  If both are given, ‘length.out’ takes priority and
     ‘times’ is ignored.

     Non-integer values of ‘times’ will be truncated towards zero.  If
     ‘times’ is a computed quantity it is prudent to add a small fuzz
     or use ‘round’.  And analogously for ‘each’.

     If ‘x’ has length zero and ‘length.out’ is supplied and is
     positive, the values are filled in using the extraction rules,
     that is by an ‘NA’ of the appropriate class for an atomic vector
     (‘0’ for raw vectors) and ‘NULL’ for a list.

_V_a_l_u_e:

     An object of the same type as ‘x’.

     ‘rep.int’ and ‘rep_len’ return no attributes (except the class if
     returning a factor).

     The default method of ‘rep’ gives the result names (which will
     almost always contain duplicates) if ‘x’ had names, but retains no
     other attributes.

_N_o_t_e:

     Function ‘rep.int’ is a simple case which was provided as a
     separate function partly for S compatibility and partly for speed
     (especially when names can be dropped).  The performance of ‘rep’
     has been improved since, but ‘rep.int’ is still at least twice as
     fast when ‘x’ has names.

     The name ‘rep.int’ long precedes making ‘rep’ generic.

     Function ‘rep’ is a primitive, but (partial) matching of argument
     names is performed as for normal functions.

     For historical reasons ‘rep’ (only) works on ‘NULL’: the resul

In [51]:
rep(1:4, 2)

[1] 1 2 3 4 1 2 3 4

In [52]:
rep(1:4, each=2)

[1] 1 1 2 2 3 3 4 4

In [55]:
rep(1:4, c(2,2,3,4))

[1] 1 1 2 2 3 3 3 4 4 4 4

In [56]:
LETTERS

[1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

In [59]:
x <- factor(LETTERS[1:4])
names(x) <- letters[1:4]
x
rep(x, 2)
rep(x, each = 2)

a b c d 
A B C D 
Levels: A B C D

a b c d a b c d 
A B C D A B C D 
Levels: A B C D

a a b b c c d d 
A A B B C C D D 
Levels: A B C D

In [60]:
mapply(rep, 1:4, 4:1)

[[1]]
[1] 1 1 1 1

[[2]]
[1] 2 2 2

[[3]]
[1] 3 3

[[4]]
[1] 4

In [62]:
noise = function(n, mean, sd){
    rnorm(n, mean, sd)
}

noise(5, 3, 3)

[1]  2.9567104  2.8878306  0.5341954  0.8735217 -2.7413348

In [64]:
mapply(noise, c(4,4,4,4), 4:7, c(3,3,3,3) )
mapply(noise, 1:5, 1:5, 2)

[,1]     [,2]     [,3]      [,4]
[1,] 4.501764 7.114038 4.954372  5.885024
[2,] 6.350176 7.786993 3.630090 11.083846
[3,] 5.219416 5.844742 5.407422  7.952227
[4,] 5.767866 3.460245 5.191620  7.606983

[[1]]
[1] 2.571521

[[2]]
[1] 2.857786 2.214328

[[3]]
[1] -0.6640032  0.5078974  5.7763768

[[4]]
[1] 1.344855 4.076448 4.383769 6.028044

[[5]]
[1] 5.321971 3.084334 4.138869 5.866261 5.735546

<h1>Instant Vectorization</h1>
If there is a function who doesn't support vectors, by using mapply kind of instantly makes it vector compatable.

<h1>tapply</h1>

In [17]:
# don't know why it's called tapply.
x = c(rnorm(10), runif(10), rnorm(10))
# gl means generate factor levels
f = gl(3, 10)
f
tapply(x, f, mean)

[1] 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3
Levels: 1 2 3

1          2          3 
0.11234250 0.43082441 0.03259096

In [68]:
str(gl)
help(gl)

function (n, k, length = n * k, labels = seq_len(n), ordered = FALSE)  


gl                    package:base                     R Documentation

_G_e_n_e_r_a_t_e _F_a_c_t_o_r _L_e_v_e_l_s

_D_e_s_c_r_i_p_t_i_o_n:

     Generate factors by specifying the pattern of their levels.

_U_s_a_g_e:

     gl(n, k, length = n*k, labels = seq_len(n), ordered = FALSE)
     
_A_r_g_u_m_e_n_t_s:

       n: an integer giving the number of levels.

       k: an integer giving the number of replications.

  length: an integer giving the length of the result.

  labels: an optional vector of labels for the resulting factor levels.

 ordered: a logical indicating whether the result should be ordered or
          not.

_V_a_l_u_e:

     The result has levels from ‘1’ to ‘n’ with each value replicated
     in groups of length ‘k’ out to a total length of ‘length’.

     ‘gl’ is modelled on the _GLIM_ function of the same name.

_S_e_e _A_l_s_o:

     The underlying ‘factor()’.

_E_x_a_m_p_l_e_s:

     ## First control, then treatment:
     gl(2, 8, labels = c("Control", "Treat"))
     ## 20 alternating 1s and 2s
     gl(2, 1, 20)
     ## alternating pairs of 1s and 2s
     gl(2, 2, 20)

In [69]:
# the default is to simplify it, if we specify not to do so, 
# we'll get 
tapply(x, f, mean, simplify=FALSE)

$`1`
[1] 0.06395474

$`2`
[1] 0.5077531

$`3`
[1] 0.3415887

In [70]:
tapply(x,f, range)

$`1`
[1] -0.9757139  1.3805296

$`2`
[1] 0.05835318 0.99358467

$`3`
[1] -1.209558  2.139424

<h2>Split</h2>

In [74]:
# Split
# split according to the factor level given
str(split)

function (x, f, drop = FALSE, ...)  


In [73]:
x = c(rnorm(10), runif(10), rnorm(10))
f = gl(3, 10)

# split always returns a list back
split(x, f)

$`1`
 [1] -0.71606726  1.99386786  0.15132051  0.16132585 -0.25492269 -1.87554620
 [7] -0.02222146 -1.11714272 -0.48472591 -2.88537016

$`2`
 [1] 0.71330566 0.69767590 0.30410992 0.97880978 0.90145610 0.28575855
 [7] 0.32928992 0.57108081 0.05083758 0.79458222

$`3`
 [1] -0.3533075  0.5343670 -0.2851771  0.9824610 -0.4507539  0.4447461
 [7]  1.7520975  0.4311749  0.2589672 -0.5135651

In [75]:
# often use lapply and split together
lapply(split(x,f), mean)

$`1`
[1] -0.5049482

$`2`
[1] 0.5626906

$`3`
[1] 0.280101

In [76]:
# use split which much more complex project
# default datasets lib
library(datasets)

In [77]:
head(airquality)

Ozone Solar.R Wind Temp Month Day
1    41     190  7.4   67     5   1
2    36     118  8.0   72     5   2
3    12     149 12.6   74     5   3
4    18     313 11.5   62     5   4
5    NA      NA 14.3   56     5   5
6    28      NA 14.9   66     5   6

In [89]:
s = split(airquality, airquality$Month)
s["7"]
lapply(s, function(x){colMeans(x[, c("Ozone", "Solar.R", "Wind")], na.rm=TRUE)})

$`7`
   Ozone Solar.R Wind Temp Month Day
62   135     269  4.1   84     7   1
63    49     248  9.2   85     7   2
64    32     236  9.2   81     7   3
65    NA     101 10.9   84     7   4
66    64     175  4.6   83     7   5
67    40     314 10.9   83     7   6
68    77     276  5.1   88     7   7
69    97     267  6.3   92     7   8
70    97     272  5.7   92     7   9
71    85     175  7.4   89     7  10
72    NA     139  8.6   82     7  11
73    10     264 14.3   73     7  12
74    27     175 14.9   81     7  13
75    NA     291 14.9   91     7  14
76     7      48 14.3   80     7  15
77    48     260  6.9   81     7  16
78    35     274 10.3   82     7  17
79    61     285  6.3   84     7  18
80    79     187  5.1   87     7  19
81    63     220 11.5   85     7  20
82    16       7  6.9   74     7  21
83    NA     258  9.7   81     7  22
84    NA     295 11.5   82     7  23
85    80     294  8.6   86     7  24
86   108     223  8.0   85     7  25
87    20      81  8.6   82     7  26
88    52      82 12.0   86     7  27
89    82     213  7.4   88     7  28
90    50     275  7.4   86     7  29
91    64     253  7.4   83     7  30
92    59     254  9.2   81     7  31

$`5`
    Ozone   Solar.R      Wind 
 23.61538 181.29630  11.62258 

$`6`
    Ozone   Solar.R      Wind 
 29.44444 190.16667  10.26667 

$`7`
     Ozone    Solar.R       Wind 
 59.115385 216.483871   8.941935 

$`8`
     Ozone    Solar.R       Wind 
 59.961538 171.857143   8.793548 

$`9`
    Ozone   Solar.R      Wind 
 31.44828 167.43333  10.18000

In [88]:
class(s)
class(s["7"])
class(s[["7"]])

[1] "list"

[1] "list"

[1] "data.frame"

In [94]:
# if we use sapply, it's going to be simplified into matrix.
sapply(s, function(x){colMeans(x[, c("Ozone", "Solar.R", "Wind")], na.rm=TRUE)})

5         6          7          8         9
Ozone    23.61538  29.44444  59.115385  59.961538  31.44828
Solar.R 181.29630 190.16667 216.483871 171.857143 167.43333
Wind     11.62258  10.26667   8.941935   8.793548  10.18000

In [95]:
# Splittin on more than one factor
x = rnorm(10)
# two grouping var here
f1 = gl(2,5)
f2 = gl(5,2)

# looks like interaction gives you mixed up factors.
# the result is also a factors
interaction(f1, f2)


[1] 1.1 1.1 1.2 1.2 1.3 2.3 2.4 2.4 2.5 2.5
Levels: 1.1 2.1 1.2 2.2 1.3 2.3 1.4 2.4 1.5 2.5

In [98]:
split(x, list(f1, f2))

$`1.1`
[1] -0.9985206  1.0213285

$`2.1`
numeric(0)

$`1.2`
[1] 0.9961229 0.1036109

$`2.2`
numeric(0)

$`1.3`
[1] 0.9944417

$`2.3`
[1] 0.08345058

$`1.4`
numeric(0)

$`2.4`
[1]  0.0567280 -0.6418684

$`1.5`
numeric(0)

$`2.5`
[1] -0.3339974  0.3551891

In [99]:
# remove empty levels by using DROP argument.
split(x, list(f1, f2), drop=TRUE)

$`1.1`
[1] -0.9985206  1.0213285

$`1.2`
[1] 0.9961229 0.1036109

$`1.3`
[1] 0.9944417

$`2.3`
[1] 0.08345058

$`2.4`
[1]  0.0567280 -0.6418684

$`2.5`
[1] -0.3339974  0.3551891

<h2> Debuggin Tools</h2>
1. Message:
2. Warning: not fatal
3. Error: Fatal Problem, stops the function
4. Condition: All three above are conditions.

In [1]:
# Warning
log(-1)

Warning message:
In log(-1): 產生了 NaNs

[1] NaN

In [2]:
# invisible, prevent auto printing
printmessage = function(x){
    if(x>0)
        print("x is greater than zero")
    else
        print("x is less than or equal to zero")

    invisible(x)
}

In [4]:
printmessage(1)
printmessage(NA)

[1] "x is greater than zero"


ERROR: Error in if (x > 0) print("x is greater than zero") else print("x is less than or equal to zero"): 需要 TRUE/FALSE 值的地方有缺值


In [6]:
printmessage_2 = function(x){
    if(is.na(x))
        print("x is a missing value")
    else if(x > 0)
        print ("x is greater than zero")
    else 
        print ("x is less than or equal to zero")
            
    invisible(x)
}

x = log(-1)
printmessage_2(x)

Warning message:
In log(-1): 產生了 NaNs

[1] "x is a missing value"


<h2> Debugging Tools in R</h2>
1. Traceback
2. debug
3. browser
4. trace
5. recover

In [9]:
# seems like we can't use the debuggin tool here Q___Q

mean(y)
traceback()

ERROR: Error in mean(y): 找不到物件 'y'


No traceback available 


In [10]:
lm(y- v)

ERROR: Error in stats::model.frame(formula = y - v, drop.unused.levels = TRUE): 找不到物件 'y'


In [11]:
traceback()

No traceback available 


In [12]:
debug(lm)

In [13]:
lm(y-x)

debugging in: lm(y - x)
debug: {
    ret.x <- x
    ret.y <- y
    cl <- match.call()
    mf <- match.call(expand.dots = FALSE)
    m <- match(c("formula", "data", "subset", "weights", "na.action", 
        "offset"), names(mf), 0L)
    mf <- mf[c(1L, m)]
    mf$drop.unused.levels <- TRUE
    mf[[1L]] <- quote(stats::model.frame)
    mf <- eval(mf, parent.frame())
    if (method == "model.frame") 
        return(mf)
    else if (method != "qr") 
        warning(gettextf("method = '%s' is not supported. Using 'qr'", 
            method), domain = NA)
    mt <- attr(mf, "terms")
    y <- model.response(mf, "numeric")
    w <- as.vector(model.weights(mf))
    if (!is.null(w) && !is.numeric(w)) 
        stop("'weights' must be a numeric vector")
    offset <- as.vector(model.offset(mf))
    if (!is.null(offset)) {
        if (length(offset) != NROW(y)) 
            stop(gettextf("number of offsets is %d, should equal %d (number of observations)", 
                length(offset), NROW(y)), 

ERROR: Error in stats::model.frame(formula = y - x, drop.unused.levels = TRUE): 找不到物件 'y'


In [14]:
Browse[2]

ERROR: Error in eval(expr, envir, enclos): 找不到物件 'Browse'


<h3>Recover</h3>

In [15]:
options(error=recover)

In [16]:
read.csv("nosuchfile.csv")

Warning message:
In file(file, "rt"): 無法開啟檔案 'nosuchfile.csv' ：No such file or directory

ERROR: Error in file(file, "rt"): 無法開啟連結
